apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coffee-stage
resources:
  - ../base/api-deployment.yml
  - ../base/api-service.yml
  - ../base/postgres-deployment.yml
  - ../base/postgres-service.yml
