apiVersion: v1
kind: Secret
metadata:
  name: coffee-app-secrets
type: Opaque
stringData:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: change_me
  DATABASE_NAME: node_course
  JWT_SECRET: change_me
  JWT_REFRESH_SECRET: change_me
